baseurl = "/"
title = "vical"
paginate = 10

pluralizelisttitles =false
enableEmoji = true
enableGitInfo = true
enableRobotsTXT=true
googleAnalytis  = ""
disqusShortname = ""
SectionPagesMenu="main"
footnoteReturnLinkContents = "↩"
pygmentsCodeFences = true

[frontmatter]
  date = ["date", ":default"]
  publishDate = ["publishDate", "date", "lastmod" ]

[params]
  description = ""
  author = ""
  hide_author = true
  show_menu = true
  powered_by = false
  images = []

[params.colors]
  black = "#000"
  white = "#fff"
  gray  = "#e9e9e9"
  dark-gray =  "hsl(0, 0%, 50%)"
  rly-dark_gray = "hsl(0, 0%, 20%)"
  primary = "#f05553"
  second = "#0098d8"
  third = "#0b3536"

[imaging]  
  quality = 85

[[menu.main]]
  name = "projects"
  weight = 1
  identifier = "projects"
  url = "/projects/"

[[menu.main]]
  name = "Blog"
  identifier = "blog"
  url = "/blog/"
  weight = 100
  
[[menu.main]]
  name = "About"
  weight = 10
  identifier = "about"
  url = "/about/me"


#[[menu.main]]
#  name = "Laboratory"
#  identifier = "labs"
#  url = "/labs/"