baseurl = "/"
languageCode = "en-us"
title = "« vicale »"
paginate = 5

pluralizelisttitles =false
enableRobotsTXT=true
googleAnalytis  = ""
disqusShortname = ""
SectionPagesMenu="main"
footnoteReturnLinkContents = "↩"

[params]
  description = ""
  author = ""
  hide_author = true
  show_menu = true
  powered_by = false
  images = []
  theme_variant = ""
  
[[menu.main]]
  name = "💼 work"
  weight = 1
  identifier = "work"
  url = "/work/"

[[menu.main]]
  name = "Astrorunners"
  parent = "work"
  identifier = "work/astrorunners"
  url = "/work/astrorunners"

[[menu.main]]
  name = "Luiza Lian"
  parent = "work"
  identifier = "work/luizalian"
  url = "/work/luizalian"

[[menu.main]]
  name = "Bigud"
  parent = "work"
  identifier = "work/bigud"
  url = "/work/bigud"

[[menu.main]]
  name = "BMG"
  parent = "work"
  identifier = "work/bmg"
  url = "/work/bmg"

[[menu.main]]
  name = "📱 apps"
  weight = 2
  identifier = "apps"
  url = "/apps/"
  
[[menu.main]]
  name = "I Ching"
  parent = "apps"
  identifier = "apps/iching"
  url = "/apps/iching"
  
[[menu.main]]
  name = "Piano Coach"
  parent = "apps"
  identifier = "apps/pianocoach"
  url = "/apps/piano-coach"

[[menu.main]]
  name = "Blog"
  identifier = "blog"
  url = "/blog/"
  weight = 10
  
[[menu.main]]
  name = "About"
  weight = 100
  identifier = "about"
  url = "/about/me"
